package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/Vanv1k/BeautyTON/internal/config"
	"github.com/Vanv1k/BeautyTON/internal/infrastructure/database/postgres"
	"github.com/Vanv1k/BeautyTON/internal/infrastructure/http/handler"
	"github.com/Vanv1k/BeautyTON/internal/infrastructure/http/router"
	"github.com/Vanv1k/BeautyTON/internal/infrastructure/storage/s3"
	"github.com/Vanv1k/BeautyTON/internal/usecase"

	_ "github.com/Vanv1k/BeautyTON/docs" // docs is generated by Swagger
)

// @title BeautyTON API
// @version 1.0
// @description This is a beauty services platform API server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /

func main() {
	cfg := config.Load()

	pg, err := postgres.NewPostgresRepo(cfg.Postgres)
	if err != nil {
		panic(fmt.Errorf("failed to init postgres: %w", err))
	}

	fileRepo, err := s3.NewFileRepository(cfg.S3)
	if err != nil {
		panic(fmt.Errorf("failed to init s3: %w", err))
	}

	// TODO: use google wire to move dependencies
	userRepo := postgres.NewUserRepository(pg)
	userPreferencesRepo := postgres.NewUserPreferencesRepository(pg)
	masterProfileRepo := postgres.NewMasterProfileRepository(pg)
	subscriptionRepo := postgres.NewSubscriptionRepository(pg)
	myMasterRepo := postgres.NewMyMasterRepository(pg)
	serviceRepo := postgres.NewServiceRepository(pg)
	serviceCategoryRepo := postgres.NewServiceCategoryRepository(pg)
	bookingRepo := postgres.NewBookingRepository(pg)
	scheduleSlotrepo := postgres.NewScheduleSlotRepository(pg)
	reviewRepo := postgres.NewReviewRepository(pg)
	paymentRepo := postgres.NewPaymentRepository(pg)
	cityRepo := postgres.NewCityRepository(pg)
	countryRepo := postgres.NewCountryRepository(pg)

	userUsecase := usecase.NewUserUsecase(userRepo, fileRepo)
	userPreferencesUsecase := usecase.NewUserPreferencesUsecase(userPreferencesRepo, userRepo, serviceCategoryRepo)
	masterProfileUsecase := usecase.NewMasterProfileUsecase(masterProfileRepo, userRepo)
	subscriptionUsecase := usecase.NewSubscriptionUsecase(subscriptionRepo, userRepo)
	myMasterUsecase := usecase.NewMyMasterUsecase(myMasterRepo, userRepo)
	serviceUsecase := usecase.NewServiceUsecase(serviceRepo, userRepo, serviceCategoryRepo, fileRepo)
	serviceCategoryUsecase := usecase.NewServiceCategoryUsecase(serviceCategoryRepo)
	bookingUsecase := usecase.NewBookingUsecase(bookingRepo, userRepo, serviceRepo)
	scheduleSlotUsecase := usecase.NewScheduleSlotUsecase(scheduleSlotrepo, masterProfileRepo, bookingRepo)
	reviewUsecase := usecase.NewReviewUsecase(reviewRepo, bookingRepo)
	paymentUsecase := usecase.NewPaymentUsecase(paymentRepo, userRepo)
	cityUsecase := usecase.NewCityUsecase(cityRepo, countryRepo)
	countryUsecase := usecase.NewCountryUsecase(countryRepo)
	fileUsecase := usecase.NewFileUsecase(fileRepo)

	userHandler := handler.NewUserHandler(userUsecase)
	userPreferencesHandler := handler.NewUserPreferencesHandler(userPreferencesUsecase)
	masterProfileHandler := handler.NewMasterProfileHandler(masterProfileUsecase)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionUsecase)
	myMasterHandler := handler.NewMyMasterHandler(myMasterUsecase)
	serviceHandler := handler.NewServiceHandler(serviceUsecase)
	serviceCategoryHandler := handler.NewServiceCategoryHandler(serviceCategoryUsecase)
	bookingHandler := handler.NewBookingHandler(bookingUsecase)
	scheduleSlotHandler := handler.NewScheduleSlotHandler(scheduleSlotUsecase)
	reviewHandler := handler.NewReviewHandler(reviewUsecase)
	paymentHandler := handler.NewPaymentHandler(paymentUsecase)
	cityHandler := handler.NewCityHandler(cityUsecase)
	countryHandler := handler.NewCountryHandler(countryUsecase)
	fileHandler := handler.NewFileHandler(fileUsecase)

	// Инициализация роутера
	r := router.NewRouter(
		userHandler,
		userPreferencesHandler,
		masterProfileHandler,
		subscriptionHandler,
		myMasterHandler,
		serviceHandler,
		serviceCategoryHandler,
		bookingHandler,
		scheduleSlotHandler,
		reviewHandler,
		paymentHandler,
		cityHandler,
		countryHandler,
		fileHandler,
	)

	// Запуск сервера
	server := &http.Server{
		Addr:         ":" + cfg.Port,
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}
	fmt.Printf("Starting server on :8080\n")
	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		panic(fmt.Errorf("failed to start server: %w", err))
	}
}
