/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IsNotMiniappRouteImport } from './routes/is-not-miniapp'
import { Route as BecomeMasterRouteImport } from './routes/become-master'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as MasterScheduleRouteImport } from './routes/master/schedule'
import { Route as MasterProfileRouteImport } from './routes/master/profile'
import { Route as MasterOnboardingRouteImport } from './routes/master/onboarding'
import { Route as MasterDashboardRouteImport } from './routes/master/dashboard'
import { Route as MasterMasterIdRouteImport } from './routes/master/$masterId'
import { Route as CatalogSearchRouteImport } from './routes/catalog/search'
import { Route as MasterMiniappSuccessRouteImport } from './routes/master/miniapp/success'
import { Route as MasterMiniappCreateRouteImport } from './routes/master/miniapp/create'
import { Route as MasterMiniappConnectRouteImport } from './routes/master/miniapp/connect'

const IsNotMiniappRoute = IsNotMiniappRouteImport.update({
  id: '/is-not-miniapp',
  path: '/is-not-miniapp',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeMasterRoute = BecomeMasterRouteImport.update({
  id: '/become-master',
  path: '/become-master',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterScheduleRoute = MasterScheduleRouteImport.update({
  id: '/master/schedule',
  path: '/master/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProfileRoute = MasterProfileRouteImport.update({
  id: '/master/profile',
  path: '/master/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterOnboardingRoute = MasterOnboardingRouteImport.update({
  id: '/master/onboarding',
  path: '/master/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDashboardRoute = MasterDashboardRouteImport.update({
  id: '/master/dashboard',
  path: '/master/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterMasterIdRoute = MasterMasterIdRouteImport.update({
  id: '/master/$masterId',
  path: '/master/$masterId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSearchRoute = CatalogSearchRouteImport.update({
  id: '/catalog/search',
  path: '/catalog/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterMiniappSuccessRoute = MasterMiniappSuccessRouteImport.update({
  id: '/master/miniapp/success',
  path: '/master/miniapp/success',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterMiniappCreateRoute = MasterMiniappCreateRouteImport.update({
  id: '/master/miniapp/create',
  path: '/master/miniapp/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterMiniappConnectRoute = MasterMiniappConnectRouteImport.update({
  id: '/master/miniapp/connect',
  path: '/master/miniapp/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-master': typeof BecomeMasterRoute
  '/is-not-miniapp': typeof IsNotMiniappRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/master/$masterId': typeof MasterMasterIdRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/onboarding': typeof MasterOnboardingRoute
  '/master/profile': typeof MasterProfileRoute
  '/master/schedule': typeof MasterScheduleRoute
  '/catalog': typeof CatalogIndexRoute
  '/master/miniapp/connect': typeof MasterMiniappConnectRoute
  '/master/miniapp/create': typeof MasterMiniappCreateRoute
  '/master/miniapp/success': typeof MasterMiniappSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-master': typeof BecomeMasterRoute
  '/is-not-miniapp': typeof IsNotMiniappRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/master/$masterId': typeof MasterMasterIdRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/onboarding': typeof MasterOnboardingRoute
  '/master/profile': typeof MasterProfileRoute
  '/master/schedule': typeof MasterScheduleRoute
  '/catalog': typeof CatalogIndexRoute
  '/master/miniapp/connect': typeof MasterMiniappConnectRoute
  '/master/miniapp/create': typeof MasterMiniappCreateRoute
  '/master/miniapp/success': typeof MasterMiniappSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-master': typeof BecomeMasterRoute
  '/is-not-miniapp': typeof IsNotMiniappRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/master/$masterId': typeof MasterMasterIdRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/onboarding': typeof MasterOnboardingRoute
  '/master/profile': typeof MasterProfileRoute
  '/master/schedule': typeof MasterScheduleRoute
  '/catalog/': typeof CatalogIndexRoute
  '/master/miniapp/connect': typeof MasterMiniappConnectRoute
  '/master/miniapp/create': typeof MasterMiniappCreateRoute
  '/master/miniapp/success': typeof MasterMiniappSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-master'
    | '/is-not-miniapp'
    | '/catalog/search'
    | '/master/$masterId'
    | '/master/dashboard'
    | '/master/onboarding'
    | '/master/profile'
    | '/master/schedule'
    | '/catalog'
    | '/master/miniapp/connect'
    | '/master/miniapp/create'
    | '/master/miniapp/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-master'
    | '/is-not-miniapp'
    | '/catalog/search'
    | '/master/$masterId'
    | '/master/dashboard'
    | '/master/onboarding'
    | '/master/profile'
    | '/master/schedule'
    | '/catalog'
    | '/master/miniapp/connect'
    | '/master/miniapp/create'
    | '/master/miniapp/success'
  id:
    | '__root__'
    | '/'
    | '/become-master'
    | '/is-not-miniapp'
    | '/catalog/search'
    | '/master/$masterId'
    | '/master/dashboard'
    | '/master/onboarding'
    | '/master/profile'
    | '/master/schedule'
    | '/catalog/'
    | '/master/miniapp/connect'
    | '/master/miniapp/create'
    | '/master/miniapp/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeMasterRoute: typeof BecomeMasterRoute
  IsNotMiniappRoute: typeof IsNotMiniappRoute
  CatalogSearchRoute: typeof CatalogSearchRoute
  MasterMasterIdRoute: typeof MasterMasterIdRoute
  MasterDashboardRoute: typeof MasterDashboardRoute
  MasterOnboardingRoute: typeof MasterOnboardingRoute
  MasterProfileRoute: typeof MasterProfileRoute
  MasterScheduleRoute: typeof MasterScheduleRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  MasterMiniappConnectRoute: typeof MasterMiniappConnectRoute
  MasterMiniappCreateRoute: typeof MasterMiniappCreateRoute
  MasterMiniappSuccessRoute: typeof MasterMiniappSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/is-not-miniapp': {
      id: '/is-not-miniapp'
      path: '/is-not-miniapp'
      fullPath: '/is-not-miniapp'
      preLoaderRoute: typeof IsNotMiniappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-master': {
      id: '/become-master'
      path: '/become-master'
      fullPath: '/become-master'
      preLoaderRoute: typeof BecomeMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/schedule': {
      id: '/master/schedule'
      path: '/master/schedule'
      fullPath: '/master/schedule'
      preLoaderRoute: typeof MasterScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/profile': {
      id: '/master/profile'
      path: '/master/profile'
      fullPath: '/master/profile'
      preLoaderRoute: typeof MasterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/onboarding': {
      id: '/master/onboarding'
      path: '/master/onboarding'
      fullPath: '/master/onboarding'
      preLoaderRoute: typeof MasterOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/dashboard': {
      id: '/master/dashboard'
      path: '/master/dashboard'
      fullPath: '/master/dashboard'
      preLoaderRoute: typeof MasterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/$masterId': {
      id: '/master/$masterId'
      path: '/master/$masterId'
      fullPath: '/master/$masterId'
      preLoaderRoute: typeof MasterMasterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/search': {
      id: '/catalog/search'
      path: '/catalog/search'
      fullPath: '/catalog/search'
      preLoaderRoute: typeof CatalogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/miniapp/success': {
      id: '/master/miniapp/success'
      path: '/master/miniapp/success'
      fullPath: '/master/miniapp/success'
      preLoaderRoute: typeof MasterMiniappSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/miniapp/create': {
      id: '/master/miniapp/create'
      path: '/master/miniapp/create'
      fullPath: '/master/miniapp/create'
      preLoaderRoute: typeof MasterMiniappCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/miniapp/connect': {
      id: '/master/miniapp/connect'
      path: '/master/miniapp/connect'
      fullPath: '/master/miniapp/connect'
      preLoaderRoute: typeof MasterMiniappConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeMasterRoute: BecomeMasterRoute,
  IsNotMiniappRoute: IsNotMiniappRoute,
  CatalogSearchRoute: CatalogSearchRoute,
  MasterMasterIdRoute: MasterMasterIdRoute,
  MasterDashboardRoute: MasterDashboardRoute,
  MasterOnboardingRoute: MasterOnboardingRoute,
  MasterProfileRoute: MasterProfileRoute,
  MasterScheduleRoute: MasterScheduleRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  MasterMiniappConnectRoute: MasterMiniappConnectRoute,
  MasterMiniappCreateRoute: MasterMiniappCreateRoute,
  MasterMiniappSuccessRoute: MasterMiniappSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
