name: Deploy Backend

on:
  push:
    branches: [develop, main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Backend
        run: |
            DEPLOY_TARGET="${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}"
            if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
              ssh -o StrictHostKeyChecking=no $DEPLOY_TARGET bash -c "'
                cd /var/www/beautyton/backend-dev || { mkdir -p /var/www/beautyton/backend-dev; cd /var/www/beautyton/backend-dev; git clone git@github.com:Vanv1k/BeautyTON.git .; }
                cd /var/www/beautyton/backend-dev
                git fetch origin
                git checkout develop
                git reset --hard origin/develop
                cd backend
                go build -o ../../app ./cmd
                systemctl restart backend-dev
              '"
            elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              ssh -o StrictHostKeyChecking=no $DEPLOY_TARGET bash -c "'
                cd /var/www/beautyton/backend-prod || { mkdir -p /var/www/beautyton/backend-prod; cd /var/www/beautyton/backend-prod; git clone git@github.com:Vanv1k/BeautyTON.git .; }
                cd /var/www/beautyton/backend-prod
                git fetch origin
                git checkout main
                git reset --hard origin/main
                cd backend
                go build -o ../../app ./cmd
                systemctl restart backend-prod
              '"
            fi