name: Deploy Backend Binary

on:
  push:
    branches: [develop, main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build binary
        run: |
          cd backend
          GOOS=linux GOARCH=amd64 go build -o app ./cmd

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Upload binary to server and restart
        run: |
          if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
            scp backend/app ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/beautyton/backend-dev/app
            ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "chmod +x /var/www/beautyton/backend-dev/app && systemctl restart backend-dev"
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            scp backend/app ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/beautyton/backend-prod/app
            ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "chmod +x /var/www/beautyton/backend-prod/app && systemctl restart backend-prod"
          fi
